# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

build-centos7:
  stage: build
  before_script:
    - mkdir ./artifacts
    - mkdir ./artifacts/centos7
  script:
    - docker build -t build-mellon-centos7 ./build/centos7
  after_script:
    - docker run -dit --name build-mellon-centos7 build-mellon-centos7
    - docker cp build-mellon-centos7:/usr/lib64/httpd/modules/mod_auth_mellon.so ./artifacts/centos7
    - docker stop build-mellon-centos7
  artifacts:
    name:
        apache-mod-mellon
    paths:
        - ./artifacts
  only:
    - master